tap "adoptopenjdk/openjdk"
tap "buildkite/buildkite"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "adr-tools"
brew "aws-vault"
brew "readline"
brew "sqlite"
brew "xz"
brew "awscli"
brew "chezmoi"
brew "direnv"
brew "fswatch"
brew "git"
brew "git-filter-repo"
brew "helm"
brew "kubectx"
brew "node"
brew "openjdk"
brew "pyenv"
brew "rbenv"
brew "terraform", link: false
brew "tfenv"
brew "zlib"
brew "buildkite/buildkite/buildkite-agent"

cask "adoptopenjdk11"
cask "adoptopenjdk8"
cask "bluesnooze"
cask "keycastr"
cask "temurin"
